// src/components/ui/button.tsx
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
  size?: 'default' | 'sm' | 'lg' | 'icon' | 'icon-sm' | 'icon-lg';
  children: React.ReactNode;
}

export default function Button({ 
  variant = 'default', 
  size = 'default', 
  className = '', 
  children, 
  ...props 
}: ButtonProps) {
  const getVariantClass = () => {
    const variants = {
      default: 'bg-blue-600 text-white hover:bg-blue-700',
      destructive: 'bg-red-600 text-white hover:bg-red-700',
      outline: 'border border-gray-300 bg-white hover:bg-gray-50',
      secondary: 'bg-gray-100 text-gray-900 hover:bg-gray-200',
      ghost: 'hover:bg-gray-100',
      link: 'text-blue-600 underline-offset-4 hover:underline'
    };
    return variants[variant] || variants.default;
  };

  const getSizeClass = () => {
    const sizes = {
      default: 'h-10 px-4 py-2',
      sm: 'h-9 rounded-md px-3',
      lg: 'h-11 rounded-md px-8',
      icon: 'h-10 w-10',
      'icon-sm': 'h-8 w-8',
      'icon-lg': 'h-12 w-12'
    };
    return sizes[size] || sizes.default;
  };

  return (
    <button
      className={`inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ${getVariantClass()} ${getSizeClass()} ${className}`}
      {...props}
    >
      {children}
    </button>
  );
}

// src/lib/components/ui/button/button.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from "svelte/elements";

	const {
		class: className,
		variant = "default",
		size = "default",
		href = undefined,
		type = "button",
		disabled,
		children,
		...restProps
	}: HTMLButtonAttributes &
		HTMLAnchorAttributes & {
			variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
			size?: "default" | "sm" | "lg" | "icon" | "icon-sm" | "icon-lg";
		} = $props();

	const baseClasses = "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4";

	const variantClasses = {
		default: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs",
		destructive: "bg-destructive hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white shadow-xs",
		outline: "bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs",
		secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-xs",
		ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
		link: "text-primary underline-offset-4 hover:underline"
	};

	const sizeClasses = {
		default: "h-9 px-4 py-2 has-[>svg]:px-3",
		sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
		lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
		icon: "size-9",
		"icon-sm": "size-8",
		"icon-lg": "size-10"
	};

	const classes = cn(
		baseClasses,
		variantClasses[variant],
		sizeClasses[size],
		className
	);
</script>

{#if href}
	<a
		class={classes}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? "link" : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		class={classes}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}
