// src/components/ui/button/index.tsx
import React from 'react';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
  size?: 'default' | 'sm' | 'lg' | 'icon';
  asChild?: React.ReactNode;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className = '', variant = 'default', size = 'default', ...props }, ref) => {
    const baseClasses = "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive";
    
    const variantClasses = {
      default: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs",
      destructive: "bg-destructive hover:bg-destructive/90 text-white shadow-xs",
      outline: "bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs",
      secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-xs",
      ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
      link: "text-primary underline-offset-4 hover:underline"
    };
    
    const sizeClasses = {
      default: "h-9 px-4 py-2",
      sm: "h-8 gap-1.5 rounded-md px-3",
      lg: "h-10 rounded-md px-6",
      icon: "size-9",
      "icon-sm": "size-8",
      "icon-lg": "size-10"
    };
    
    const classes = `${baseClasses} ${variantClasses[variant]} ${sizeClasses[size]} ${className}`.trim();

    return (
      <button className={classes} ref={ref} {...props} />
    );
  }
);

Button.displayName = 'Button';

export { Button };

// src/lib/components/ui/button/button.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from "svelte/elements";

	const {
		class: className,
		variant = "default",
		size = "default",
		href = undefined,
		type = "button",
		disabled,
		children,
		...restProps
	}: HTMLButtonAttributes &
		HTMLAnchorAttributes & {
			variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
			size?: "default" | "sm" | "lg" | "icon" | "icon-sm" | "icon-lg";
		} = $props();

	const baseClasses = "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4";

	const variantClasses = {
		default: "bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs",
		destructive: "bg-destructive hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white shadow-xs",
		outline: "bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs",
		secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-xs",
		ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
		link: "text-primary underline-offset-4 hover:underline"
	};

	const sizeClasses = {
		default: "h-9 px-4 py-2 has-[>svg]:px-3",
		sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
		lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
		icon: "size-9",
		"icon-sm": "size-8",
		"icon-lg": "size-10"
	};

	const classes = cn(
		baseClasses,
		variantClasses[variant],
		sizeClasses[size],
		className
	);
</script>

{#if href}
	<a
		class={classes}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? "link" : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		class={classes}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}
