// src/lib/components/StatusComposer.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  let statusText = '';
  let showEmojis = false;
  const dispatch = createEventDispatcher();

  function postStatus() {
    if (statusText.trim()) {
      console.log('Posting status:', statusText);
      statusText = '';
      dispatch('refresh');
    }
  }

  function addEmoji(emoji: string) {
    console.log('Emoji clicked:', emoji);
    statusText += emoji;
    showEmojis = false;
  }

  function toggleEmojiPanel() {
    console.log('Toggling emoji panel');
    showEmojis = !showEmojis;
  }
</script>

<div class="mb-4 bg-white">
  <div class="flex space-x-3">
    <div class="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center text-white font-bold">
      我
    </div>
    
    <div class="flex-1">
      <textarea
        bind:value={statusText}
        placeholder="说点什么吧..."
        class="w-full min-h-[80px] p-3 border border-gray-300 rounded-md resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
        rows="3"
      />
      
      <div class="flex items-center justify-between mt-3">
        <div class="flex space-x-2">
          <button
            type="button"
            class="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center space-x-1"
            on:click={toggleEmojiPanel}
          >
            <span>😊</span>
            <span>表情</span>
          </button>
          
          <button type="button" class="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center space-x-1">
            <span>📷</span>
            <span>图片</span>
          </button>
          
          <button type="button" class="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center space-x-1">
            <span>🎵</span>
            <span>音乐</span>
          </button>
          
          <button type="button" class="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center space-x-1">
            <span>📹</span>
            <span>视频</span>
          </button>
        </div>
        
        <button
          type="button"
          disabled={!statusText.trim()}
          on:click={postStatus}
          class="px-4 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          发布
        </button>
      </div>

      {#if showEmojis}
        <div class="mt-3 p-3 bg-gray-50 rounded-lg border border-gray-200">
          <div class="grid grid-cols-8 gap-1">
            {#each [
              '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨'
            ] as emoji}
              <button
                type="button"
                class="text-xl p-2 hover:bg-gray-100 rounded"
                on:click={() => addEmoji(emoji)}
              >
                {emoji}
              </button>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  /* 确保按钮有合适的样式 */
  button {
    cursor: pointer;
  }
  
  button:disabled {
    cursor: not-allowed;
  }
</style>

// src/components/home/StatusComposer.tsx
import React, { useState } from 'react';
import Button from '../ui/button';
import { Avatar } from '../ui/avatar';

interface StatusComposerProps {
  onPost?: (content: string, imageUrl: string) => void;
}

export default function StatusComposer({ onPost }: StatusComposerProps) {
  const [showEmoji, setShowEmoji] = useState(false);
  const [content, setContent] = useState('');
  const [imageUrl, setImageUrl] = useState('');

  const commonEmojis = ['😊', '😂', '❤️', '👍', '🎉', '🔥', '💯', '🎁', '🌟', '✨', '🎨', '🎭', '🍅', '🥳', '🚗'];

  const handlePost = () => {
    if (content.trim() || imageUrl) {
      onPost?.(content, imageUrl);
      setContent('');
      setImageUrl('');
      setShowEmoji(false);
    }
  };

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6">
      <h2 className="text-lg font-semibold mb-4">分享你的新鲜事...</h2>
      
      <div className="space-y-4">
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="说点什么吧..."
          className="w-full p-3 border rounded-lg resize-none"
          style={{ borderColor: 'var(--renren-border)' }}
          rows={4}
        />
        
        {imageUrl && (
          <div className="mt-2">
            <img 
              src={imageUrl} 
              alt="Preview" 
              className="max-w-full h-48 object-cover rounded-lg"
              style={{ border: '1px solid var(--renren-border)' }}
            />
            <Button 
              size="sm" 
              onClick={() => setImageUrl('')}
              className="mt-2"
            >
              删除图片
            </Button>
          </div>
        )}
        
        <div className="flex items-center justify-between">
          <div className="flex space-x-2">
            <div className="relative">
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => setShowEmoji(!showEmoji)}
                className="text-lg"
              >
                😊
              </Button>
              
              {showEmoji && (
                <div className="absolute top-10 left-0 bg-white border border-gray-200 w-80 rounded-lg shadow-lg p-3 z-10">
                  <div className="grid grid-cols-5 gap-1">
                    {commonEmojis.map((emoji) => (
                      <button
                        key={emoji}
                        onClick={() => setContent(content + emoji)}
                        className="text-xl p-1 hover:bg-gray-100 rounded"
                      >
                        {emoji}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
            
            <Button variant="outline" size="sm">📷</Button>
            <Button variant="outline" size="sm">🎵</Button>
            <Button variant="outline" size="sm">🔗</Button>
          </div>
          
          <div className="flex space-x-2">
            <Button 
              onClick={handlePost}
              disabled={!content.trim() && !imageUrl}
              className="px-6"
            >
              发布
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
